<select name="category" onchange="setNewCategory(this.value);">	<option value="Bank Fees: Exchange charges">Bank Fees: Exchange charges
	</option><option value="Bank fees and charges">Bank fees and charges
	</option><option value="Bills: Electricity">Bills: Electricity
	</option><option value="Bills: Margs rates">Bills: Margs rates
	</option><option value="Bills: Rates">Bills: Rates
	</option><option value="Bills: Water and sewerage">Bills: Water and sewerage
	</option><option value="Bills: gas">Bills: gas
	</option><option value="Books">Books
	</option><option value="Cash withdrawals">Cash withdrawals
	</option><option value="Childcare">Childcare
	</option><option value="Clothes: Ivan">Clothes: Ivan
	</option><option value="Clothes: Kids">Clothes: Kids
	</option><option value="Clothes: Outdoor">Clothes: Outdoor
	</option><option value="Clothes: Shoes">Clothes: Shoes
	</option><option value="Credit card payments">Credit card payments
	</option><option value="Department Stores: Anaconda">Department Stores: Anaconda
	</option><option value="Department Stores: Big W">Department Stores: Big W
	</option><option value="Department Stores: David Jones">Department Stores: David Jones
	</option><option value="Department Stores: Harris Scarfe">Department Stores: Harris Scarfe
	</option><option value="Department Stores: Kathmandu">Department Stores: Kathmandu
	</option><option value="Department Stores: Macpac">Department Stores: Macpac
	</option><option value="Department Stores: Myer">Department Stores: Myer
	</option><option value="Department Stores: Rebel">Department Stores: Rebel
	</option><option value="Department Stores: Target">Department Stores: Target
	</option><option value="Entertainment: Movie rentals">Entertainment: Movie rentals
	</option><option value="Entertainment: Movies">Entertainment: Movies
	</option><option value="Entertainment: Shows and events">Entertainment: Shows and events
	</option><option value="Finance: Larissa IGB">Finance: Larissa IGB
	</option><option value="Finance: Ronan IGB">Finance: Ronan IGB
	</option><option value="Finance: Tax payments and accountant fees">Finance: Tax payments and accountant fees
	</option><option value="Food: Work lunches">Food: Work lunches
	</option><option value="Food: eating out">Food: eating out
	</option><option value="Gifts: Ivan">Gifts: Ivan
	</option><option value="Gifts: Melbourne rellies">Gifts: Melbourne rellies
	</option><option value="Gifts: Rachael">Gifts: Rachael
	</option><option value="Gracemere: Loan repayments">Gracemere: Loan repayments
	</option><option value="Gracemere: Miscellaneous">Gracemere: Miscellaneous
	</option><option value="Gracemere: Water">Gracemere: Water
	</option><option value="Gracemere: rates">Gracemere: rates
	</option><option value="Gracemere: rental income">Gracemere: rental income
	</option><option value="Groceries">Groceries
	</option><option value="Haircuts">Haircuts
	</option><option value="Hapkido">Hapkido
	</option><option value="Hardware">Hardware
	</option><option value="Health insurance">Health insurance
	</option><option value="Health: Dentist">Health: Dentist
	</option><option value="Health: Doctor">Health: Doctor
	</option><option value="Health: Imaging">Health: Imaging
	</option><option value="Health: pharmacy">Health: pharmacy
	</option><option value="Health: psychology">Health: psychology
	</option><option value="Hobbies: Arts and Crafts">Hobbies: Arts and Crafts
	</option><option value="Holiday: USA 2012">Holiday: USA 2012
	</option><option value="Holidays: Carnival Spirit 2015">Holidays: Carnival Spirit 2015
	</option><option value="Holidays: travel">Holidays: travel
	</option><option value="House: Loan repayments">House: Loan repayments
	</option><option value="House: Miscellaneous costs">House: Miscellaneous costs
	</option><option value="House: Repairs">House: Repairs
	</option><option value="House: furniture">House: furniture
	</option><option value="Income: Ivan">Income: Ivan
	</option><option value="Income: Rachael">Income: Rachael
	</option><option value="Income: Solar cells">Income: Solar cells
	</option><option value="Insurance: Car">Insurance: Car
	</option><option value="Insurance: Health">Insurance: Health
	</option><option value="Insurance: Income protection">Insurance: Income protection
	</option><option value="Insurance: home">Insurance: home
	</option><option value="Kids: Toys">Kids: Toys
	</option><option value="Landscaping">Landscaping
	</option><option value="Larissa: Clothes">Larissa: Clothes
	</option><option value="Larissa: Orthodontist">Larissa: Orthodontist
	</option><option value="Larissa: Travel">Larissa: Travel
	</option><option value="Larissa: savings">Larissa: savings
	</option><option value="Life insurance">Life insurance
	</option><option value="Mobile phones">Mobile phones
	</option><option value="Musical instruments and stuff">Musical instruments and stuff
	</option><option value="Phones: TransACT">Phones: TransACT
	</option><option value="Rachael: Extra stuff">Rachael: Extra stuff
	</option><option value="Reimbursed expenses">Reimbursed expenses
	</option><option value="Ronan: Scouts">Ronan: Scouts
	</option><option value="Ronan: savings">Ronan: savings
	</option><option value="School: IMP">School: IMP
	</option><option value="School: Lyneham High">School: Lyneham High
	</option><option value="School: Turner">School: Turner
	</option><option value="Shopping: Miscellaneous">Shopping: Miscellaneous
	</option><option value="Sports: Hapkido">Sports: Hapkido
	</option><option value="Sports: Ice skating">Sports: Ice skating
	</option><option value="Sports: Rachael fitness">Sports: Rachael fitness
	</option><option value="Sports: Soccer">Sports: Soccer
	</option><option value="Sports: Swimming">Sports: Swimming
	</option><option value="Sports: Tennis">Sports: Tennis
	</option><option value="Sports: yoga">Sports: yoga
	</option><option value="Stationery">Stationery
	</option><option value="Stores: JB Hifi">Stores: JB Hifi
	</option><option value="Take-away">Take-away
	</option><option value="Teaching expenses">Teaching expenses
	</option><option value="Technology: Apple Store Canberra">Technology: Apple Store Canberra
	</option><option value="Technology: Computers and stuff">Technology: Computers and stuff
	</option><option value="Technology: Electronics">Technology: Electronics
	</option><option value="Technology: Games">Technology: Games
	</option><option value="Technology: ISP">Technology: ISP
	</option><option value="Technology: Photography and video">Technology: Photography and video
	</option><option value="Technology: Streaming services">Technology: Streaming services
	</option><option value="Technology: iTunes Store">Technology: iTunes Store
	</option><option value="Transport: ACTION">Transport: ACTION
	</option><option value="Transport: Car">Transport: Car
	</option><option value="Transport: Car lease">Transport: Car lease
	</option><option value="Transport: Car rego">Transport: Car rego
	</option><option value="Transport: Car repairs and maintenance">Transport: Car repairs and maintenance
	</option><option value="Transport: Car servicing">Transport: Car servicing
	</option><option value="Transport: Fuel">Transport: Fuel
	</option><option value="Transport: Misc">Transport: Misc
	</option><option value="Transport: Parking">Transport: Parking
	</option><option value="Transport: Taxis">Transport: Taxis
	</option><option value="Transport: bicycles">Transport: bicycles
	</option><option value="Travel: Insurance">Travel: Insurance
	</option><option value="Travel: accommodation">Travel: accommodation
	</option><option value="Travel: activities">Travel: activities
	</option><option value="Vet">Vet
	</option><option value="ZZZ: Internal transactions">ZZZ: Internal transactions
	</option><option value="ZZZ: Visa card topups">ZZZ: Visa card topups
	</option><option value="eBay">eBay
</option><option selected="" value="Not set">Not set
</option></select>